# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e1a62054a996e0d9f8852182edae2777c97da2057acbc2d313edb78f06751093b381af84b7a9bcafb2cac5b0915a070309de51de00188dd37286039fad26b06

test:
  secret_key_base: 76f676ed9439f4901e45353df985b4c74d6b92882755bb4867f49142fda4d2730867a784e20c2d36ffbebba754f0905093a8fd5c6086497458e844033f99ec38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
